apiVersion: apps/v1
kind: Deployment
metadata:
  name: peet-server-sandbox
spec:
  replicas: 1
  selector:
    matchLabels:
      app: peet-sandbox
  template:
    metadata:
      labels:
        app: peet-sandbox
    spec:
      containers:
        - name: peet-sandbox
          image: adithyam297/peet-sandbox
