apiVersion: v1
kind: Service
metadata:
  name: peet-server-cluster-ip
spec:
  type: ClusterIP
  selector:
    app: peet-server
  ports:
    - port: 3000
      targetPort: 3000
---
apiVersion: v1
kind: Service
metadata:
  name: peet-server-node-port
spec:
  type: NodePort
  ports:
    - port: 3000
      targetPort: 3000
      nodePort: 30001
  selector:
    app: peet-server